version: '3'

services:
  file-parser-service:
    build: app/file-parser-service
    container_name: file-parser-service
    environment:
      SERVER_PORT: "8080"
      NODE_ENV: "prod"
      LOG_LEVEL: "debug"
      DB_HOST: "mongo"
      DB_NAME: "db_name"
      DB_USERNAME: "root"
      DB_PASSWORD: "pass-123"
      DB_COLLECTION: "incidents"
    networks:
      - esnet
    depends_on:
      - mongo

  es01:
    build: etc/elasticsearch/docker/
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - node.ml=false
      - xpack.ml.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es.data:/var/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      esnet:
        aliases:
            - elasticsearch 
      
  kibana:
    build: etc/kibana/docker/
    container_name: kibana
    environment:
      - SERVER_NAME='localhost'
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_URL=http://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_HOST=es01
      - ELASTICSEARCH_PORT=9200
      - ELASTIC_PWD=changeme
      - KIBANA_PWD=changeme
    ports:
      - 8082:5601
    depends_on:
      - es01    
    networks:
      - esnet

  mongo:
    build: etc/db/docker/
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass-123
    networks:
      - esnet

  logstash:
    build: etc/logstash/docker
    container_name: logstash
    #The host ip where the mysql is running
#    extra_hosts:
#       db: mongo
    volumes:
      - ./etc/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./etc/logstash/config/pipeline/:/usr/share/logstash/pipeline/
      - ./etc/logstash/var/lastrun:/root/.logstash_jdbc_last_run
    ports:
      - '5001:5001'
    environment:
      - DB_HOST=mongo
      - DB_NAME=db_name
      - DB_USERNAME=root
      - DB_PASSWORD=pass-123
      - DB_COLLECTION=incidents
      - ELASTICSEARCH_INDEX=itsm_incidents
    networks:
      - esnet
    depends_on:
      - es01
      
volumes:
  es.data:
    driver: local
    
networks:
  esnet: